### PR TITLE
Fix: nested route not allowed for css plugin

### LINKED ISSUE #21: [BUG] pluginCssBundle doesn't resolve locations correctly
**Describe the bug**
Css plugin paths are not being resolved correctly

**To Reproduce**
Specify any route in the css configuration `output` option that isn't located in the root of the output folder.

**Expected behavior**
Should create the folder and emit the file

Similar solution to #16

### PR DESCRIPTION
**Pull request by Soremwar**
Fixes #21

### CODE REVIEW

**Comment by Soremwar** [comment]
Good thing CI is free

**Comment by Soremwar** [comment]
Thinking it through, it should be the emitter the one who validates the path instead of adding ensureDir everywhere
Dummy me

**Comment by Soremwar** [comment]
Let's merge this as is and add it to the TODO list XD

**Review by jeroenptrs — APPROVED** [review]
ensuredir would probably be handled by node Rollup so yeah, fine for now 👍

**Pull request merged**
